apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-blue
spec:
  selector:
    matchLabels:
      app: myapp
      env: blue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
        env: blue
    spec:
      containers:
      - name: myapp
        image: registry-1.docker.io/anjoysutrisna/custom-nginx:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 1Gi
